<?php

namespace dekuan\deuclientpro;


/**
 *	Created by PhpStorm.
 *	User: xing
 *	Date: 11:36 AM December 13, 2017
 *	Time: 
 */
class UCProError
{
	//
	//	error ids
	//
	const SUCCESS								= 0;		//	successfully


	
	
	
	
	//
	//	src/UClientPro.php
	//
	const UCLIENTPRO_MAKELOGIN_FAILURE					= 10000;

	const UCLIENTPRO_CHECKLOGIN_FAILURE					= 10100;
	const UCLIENTPRO_CHECKLOGIN_SESSION_TIMEOUT				= 10101;
	

	//
	//	src/Models/UCProMain.php
	//
	const MODELS_UCPROMAIN_MAKELOGINBYXTARRAY_FAILURE			= 12000;
	
	const MODELS_UCPROMAIN_MAKELOGINBYCOOKIESTRING_FAILURE			= 12100;
	const MODELS_UCPROMAIN_MAKELOGINBYCOOKIESTRING_PARAM_COOKIESTRING	= 12110;
	const MODELS_UCPROMAIN_MAKELOGINBYCOOKIESTRING_INVALID_COOKIE		= 12120;


	//
	//	src/Models/UCProXT.php
	//
	const MODELS_UCPROXT_FLASHXTARRAY_FAILURE				= 12200;
	const MODELS_UCPROXT_FLASHXTARRAY_PARAM_ARRDATA				= 12210;
	const MODELS_UCPROXT_FLASHXTARRAY_PARAM_CKX				= 12211;
	const MODELS_UCPROXT_FLASHXTARRAY_PARAM_CKT				= 12212;

	const MODELS_UCPROXT_CHECKXTARRAY_FAILURE				= 12300;
	const MODELS_UCPROXT_CHECKXTARRAY_BAD_COOKIE				= 12330;
	const MODELS_UCPROXT_CHECKXTARRAY_INVALID_CHECKSUM_MD5			= 12331;
	const MODELS_UCPROXT_CHECKXTARRAY_INVALID_CHECKSUM_CRC			= 12332;



	//
	//	src/Models/UCProCookie.php
	//
	const MODELS_UCPROCOOKIE_MSETCOOKIEBYCOOKIEARRAY_FAILURE		= 15000;
	const MODELS_UCPROCOOKIE_MSETCOOKIEBYCOOKIEARRAY_PARAM_COOKIE		= 15010;

	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGIN_FAILURE			= 15100;
	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGIN_PARAM_COOKIE		= 15110;
	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGIN_SET_COOKIE			= 15115;
	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGOUT_SET_COOKIE			= 15120;

	const MODELS_UCPROCOOKIE_SETCOOKIES_FAILURE				= 15200;
	const MODELS_UCPROCOOKIE_SETCOOKIES_PARAM_COOKIE			= 15210;
	const MODELS_UCPROCOOKIE_SETCOOKIES_PARAM_TMEXPIRE			= 15211;



}
