<?php

namespace dekuan\deuclientpro;


/**
 *	Created by PhpStorm.
 *	User: xing
 *	Date: 11:36 AM December 13, 2017
 *	Time: 
 */
class UCProError
{
	//
	//	error ids
	//
	const SUCCESS								= 0;		//	successfully


	
	
	
	
	//
	//	src/UClientPro.php
	//
	const UCLIENTPRO_MAKELOGIN_FAILURE					= 10000;

	const UCLIENTPRO_CHECKLOGIN_FAILURE					= 10100;
	const UCLIENTPRO_CHECKLOGIN_SESSION_TIMEOUT				= 10101;
	
	const UCLIENTPRO_CHECKSESSION_FAILURE					= 10220;
	const UCLIENTPRO_CHECKSESSION_INVALID_RETURN				= 10230;


	//
	//	src/UCProSession.php
	//
	const UCPROSESSION_CHECKSESSIONBYRPC_PARAM				= 11000;
	const UCPROSESSION_CHECKSESSIONBYRPC_PARAM_MID				= 11001;
	const UCPROSESSION_CHECKSESSIONBYRPC_PARAM_SS_ID			= 11002;
	const UCPROSESSION_CHECKSESSIONBYRPC_PARAM_SS_URL			= 11003;
	const UCPROSESSION_CHECKSESSIONBYRPC_PARAM_SS_URL2			= 11004;
	const UCPROSESSION_CHECKSESSIONBYRPC_FAILURE				= 11020;
	const UCPROSESSION_CHECKSESSIONBYRPC_INVALID_VDATA			= 11030;
	
	
	
	
	
	//
	//	src/Models/UCProMain.php
	//
	const MODELS_UCPROMAIN_MAKELOGINBYXTARRAY_FAILURE			= 15000;
	
	const MODELS_UCPROMAIN_MAKELOGINBYCOOKIESTRING_FAILURE			= 15100;
	const MODELS_UCPROMAIN_MAKELOGINBYCOOKIESTRING_PARAM_COOKIESTRING	= 15110;
	const MODELS_UCPROMAIN_MAKELOGINBYCOOKIESTRING_INVALID_COOKIE		= 15120;


	//
	//	src/Models/UCProXT.php
	//
	const MODELS_UCPROXT_FLASHXTARRAY_FAILURE				= 15200;
	const MODELS_UCPROXT_FLASHXTARRAY_PARAM_ARRDATA				= 15210;
	const MODELS_UCPROXT_FLASHXTARRAY_PARAM_CKX				= 15211;
	const MODELS_UCPROXT_FLASHXTARRAY_PARAM_CKT				= 15212;

	const MODELS_UCPROXT_CHECKXTARRAY_FAILURE				= 15300;
	const MODELS_UCPROXT_CHECKXTARRAY_BAD_COOKIE				= 15330;
	const MODELS_UCPROXT_CHECKXTARRAY_INVALID_CHECKSUM_MD5			= 15331;
	const MODELS_UCPROXT_CHECKXTARRAY_INVALID_CHECKSUM_CRC			= 15332;



	//
	//	src/Models/UCProCookie.php
	//
	const MODELS_UCPROCOOKIE_MSETCOOKIEBYCOOKIEARRAY_FAILURE		= 18000;
	const MODELS_UCPROCOOKIE_MSETCOOKIEBYCOOKIEARRAY_PARAM_COOKIE		= 18010;

	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGIN_FAILURE			= 18100;
	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGIN_PARAM_COOKIE		= 18110;
	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGIN_SET_COOKIE			= 18115;
	const MODELS_UCPROCOOKIE_SETCOOKIESFORLOGOUT_SET_COOKIE			= 18120;

	const MODELS_UCPROCOOKIE_SETCOOKIES_FAILURE				= 18200;
	const MODELS_UCPROCOOKIE_SETCOOKIES_PARAM_COOKIE			= 18210;
	const MODELS_UCPROCOOKIE_SETCOOKIES_PARAM_TMEXPIRE			= 18211;



}
